In [1]:
import sklearn
sklearn.__version__   # 버전 확인

'0.21.2'

In [2]:
    # 1
# 데이터 불러오기 - load계열의 명령들은 설치 패키지에 저장되어 있어서 별도로 다운받지 않아도 바로 쓸 수 있는 데이터를 제공
# load_boston, load_diabetes, load_linnerud, load_iris, load_digits, load_wine
from sklearn.datasets import load_iris

In [3]:
iris_dataset = load_iris()
print('iris_dataset key : {}'.format(iris_dataset.keys()))

iris_dataset key : dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print(iris_dataset['data'][:10])
print('shape of data : {}'.format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
shape of data : (150, 4)


In [5]:
print(iris_dataset['feature_names'])     # feature : 독립변수

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [7]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
# 학습을 위한 데이터와 성능 평가를 위한 평가 데이터로 분리
data = iris_dataset['data']
target = iris_dataset['target']

In [9]:
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                    target,
                                                                    test_size = 0.25,   # 0.25 : 25% -> 테스트할 때 25%, 학습할 때 75% 사용하겠다는 뜻
                                                                    random_state = 42)

In [13]:
print('shape of train input : {}'.format(train_input.shape))
print('shape of test input : {}'.format(test_input.shape))
print('shape of train label : {}'.format(train_label.shape))
print('shape of test label : {}'.format(test_label.shape))

shape of train input : (112, 4)
shape of test input : (38, 4)
shape of train label : (112,)
shape of test label : (38,)


In [14]:
# 지도학습 - 분류
# k-최근접 이웃 분류기 (K-Nearest Neighbor) (가장 가까운 값 k를 찾음)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)   # k값 1개를 찾겠다

In [15]:
knn.fit(train_input, train_label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [16]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

In [17]:
knn.predict(new_input)

array([1])

In [18]:
predict_label = knn.predict(test_input)
print(predict_label)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [19]:
print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

test accuracy 1.00


In [20]:
    # 2
from sklearn.datasets import load_iris

In [21]:
data = iris_dataset['data']
target = iris_dataset['target']

In [22]:
# 비지도학습 - 군집
# K-means Clustering(평균 군집)
from sklearn.model_selection import train_test_split

In [23]:
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                    target,
                                                                    test_size = 0.25,   
                                                                    random_state = 42)

In [25]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters = 3)

In [26]:
k_means.fit(train_input)    # 비지도학습이므로 답은 넣지 않고, 데이터값만 넣음

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [27]:
k_means.labels_

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 1,
       1, 0, 2, 1, 0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0,
       2, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 2, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0,
       2, 2, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 2])

In [28]:
print('0 cluster : ', train_label[k_means.labels_ == 0])    # train_label : train_input에 의해서 매치되는 label값
print('1 cluster : ', train_label[k_means.labels_ == 1])
print('2 cluster : ', train_label[k_means.labels_ == 2])

0 cluster :  [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]
1 cluster :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 cluster :  [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]


In [29]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

In [30]:
prediction = k_means.predict(new_input)

In [32]:
predict_cluster = k_means.predict(test_input)
print(predict_cluster)

[0 1 2 0 0 1 0 2 0 0 2 1 1 1 1 0 2 0 0 2 1 0 1 2 2 2 2 2 1 1 1 1 0 1 1 0 0
 1]


In [40]:
# 특징 추출 - CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer    # feature : 독립변수(입력해주는 값)

In [41]:
text_data = ['나는 배가 고프다', '점심 뭐 먹지', '내일 공부 해야겠다', '점심 먹고 공부 해야지']

count_vectorizer = CountVectorizer()

In [42]:
count_vectorizer.fit(text_data)
print(count_vectorizer.vocabulary_)   # 하나의 사전 생성 - ㄱㄴㄷ순으로 1, 2, 3 순서가 매겨짐

{'나는': 2, '배가': 6, '고프다': 0, '점심': 7, '먹지': 5, '내일': 3, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [43]:
sentence = [text_data[0]]  # ['나는 배가 고프다']
print(count_vectorizer.transform(sentence).toarray())   # sentence를 만들어 놓은 사전 정보를 바탕으로 vectorize

[[1 0 1 0 0 0 1 0 0 0]]


In [48]:
# 특징 추출 - TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
text_data = ['나는 배가 고프다', '점심 뭐 먹지', '내일 공부 해야겠다', '점심 먹고 공부 해야지']

tfidf_vectorizer = TfidfVectorizer()

In [50]:
tfidf_vectorizer.fit(text_data)
print(tfidf_vectorizer.vocabulary_)

{'나는': 2, '배가': 6, '고프다': 0, '점심': 7, '먹지': 5, '내일': 3, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [51]:
# tf : 문장에서의 빈도수 - 자주 나오면 점수를 높게 줌 / i : df값의 역수를 취함 - 전체에서 자주 나오면 점수를 낮게 줌 / df : 전체에서의 빈도수 
sentence = [text_data[3]]   # ['점심 먹고 공부 해야지']
print(tfidf_vectorizer.transform(sentence).toarray()) 

[[0.         0.43779123 0.         0.         0.55528266 0.
  0.         0.43779123 0.         0.55528266]]
